"""Add relation to db

Revision ID: 11ef1dbea703
Revises: e5273365dce2
Create Date: 2024-07-18 16:21:40.422096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ef1dbea703'
down_revision: Union[str, None] = 'e5273365dce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_type_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_country_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'types', ['type_id'], ['type_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'countries', ['country_id'], ['country_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_country_id_fkey', 'projects', 'countries', ['country_id'], ['country_id'])
    op.create_foreign_key('projects_type_id_fkey', 'projects', 'types', ['type_id'], ['type_id'])
    # ### end Alembic commands ###
