"""Add versions3 and add another id and project_id

Revision ID: 74b0405b5bf1
Revises: 0070733235f8
Create Date: 2024-07-14 21:00:29.531222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b0405b5bf1'
down_revision: Union[str, None] = '0070733235f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'id')
    # ### end Alembic commands ###
